### ISSUE TITLE
Scrolling beyond the window edge seems broken

### ISSUE THREAD

**Issue by aalekseyev** [aspiers/smooth-scrolling#14] opened 2015-11-26 14:36 UTC
If I put my cursor on the first line of the window and press C-p the behavior is bad. In particular, if you do C-p C-n C-p, then the third keystroke (the second C-p) is not a no-op. Indeed, the first C-p sometimes jumps the window by huge amounts, probably because the standard emacs scrolling logic kicks in. 

Same applies to the last line of the window and C-n.

**Comment by aspiers** [comment] 2016-02-27 16:31
Since merging #10 I can't reproduce this (and I forgot to try before merging).  Can you?

**Comment by aspiers** [comment] 2016-10-02 19:50
No reply so I'm closing - if you still see this then please let me know and we can reopen.  Thanks!

**Closed by aspiers** 2016-10-02 19:50 UTC
